import { Inter, Roboto_Mono } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Navigation from './components/navigation';

// Define your fonts
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
        <body className="font-sans antialiased">
          <header className="flex flex-col bg-gray-800 text-white">
            <div className="flex items-center justify-between p-4">
              <h1 className="text-2xl font-bold">Let's start Next.js</h1>
            </div>
            <Navigation />
          </header>
          {children}
          <footer className="flex items-center justify-center p-4 bg-gray-800 text-white">
            <p className="text-sm">© {new Date().getFullYear()} Next.js App</p>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}